name: Monkey Auto

on:
  # 每天 UTC 18:00 自动运行
  schedule:
    - cron: '10 18 * * *'

  # 手动运行
  workflow_dispatch:

permissions:
  contents: read

jobs:
  monkey:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      # =========================
      # 📥 检出私库 monkey-auto
      # =========================
      - name: Checkout private repo (monkey-auto)
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/monkey-auto
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: scripts

      # =========================
      # 🐍 Python
      # =========================
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # =========================
      # 📦 安装依赖
      # =========================
      - name: Install deps
        working-directory: scripts
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # =========================
      # 🚀 执行脚本
      # =========================
      - name: Run Monkey
        working-directory: scripts
        env:
          monkey_email: ${{ secrets.MONKEY_EMAIL }}
          monkey_password: ${{ secrets.MONKEY_PASSWORD }}

          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          python monkey.py